### ISSUE TITLE
Cannot install in bitnami 3.4 instance (possible conflict with plugins?)

### ISSUE THREAD

**Issue by MatthewPaulGithub** [chriswnl/redmine_google_authenticator#1]
Looks like this is a work in progress, but I'm leaving this here in case it helps. When I install on bitnami 3.4 instance, I get the message below.

***NOTE - not expecting any fix etc, this isn't listed on the official redmine plugins so I assume it's for your own use - but it would be very cool if you did fix/list it on redmine.org - I haven't seen any other plugin using the google 2FA so it would be an excellent feature. All the best!***

bitnami@ip-172-30-0-36:/opt/bitnami/apps/redmine/htdocs/plugins$ rake redmine:plugins:migrate RAILS_ENV=production
(in /opt/bitnami/apps/redmine/htdocs)
rake aborted!
LoadError: Unable to autoload constant AccountControllerPatch, expected /opt/bitnami/apps/redmine/htdocs/plugins/google_authenticator/lib/account_controller_patch.rb to define it
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_local_avatars/init.rb:33:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'

Caused by:
Polyglot::PolyglotLoadError: Failed to load /opt/bitnami/apps/redmine/htdocs/config/environment using extensions rb
/opt/bitnami/apps/redmine/htdocs/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)

Probably because I have a lot of plugins etc -

nvironment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Cvs                            1.12.13
  Git                            2.14.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.4.0
  computed_custom_field          1.0.6
  custom_menu                    1.8.0
  easy_gantt                     1.10
  easy_mindmup                   1.2
  easy_wbs                       1.7
  external_links_in_new_window   0.9
  issue_charts                   1.3.0
  issue_hot_buttons              0.4.4
  issue_mail_with_attachments    0.2.0
  projects_tree_view             0.0.8
  recurring_tasks                2.0.0-pre
  redmine_agile                  1.4.5
  redmine_anonymous_watchers     0.2.0
  redmine_autoclose              0.0.4
  redmine_banner                 0.1.2
  redmine_base_deface            0.0.1
  redmine_boards_watchers        0.2.7
  redmine_custom_workflows       0.1.6
  redmine_customize_core_fields  1.0.0
  redmine_editauthor             0.11.0
  redmine_email_fetcher          0.3.1
  redmine_image_clipboard_paste  3.3.0
  redmine_impersonate            0.10.0
  redmine_incoming_emails        0.0.1
  redmine_issue_tabs             1.2.2
  redmine_language_change        0.1.0
  redmine_lightbox2              0.3.2
  redmine_local_avatars          1.0.3
  redmine_login_audit            0.3.1
  redmine_mentions               0.0.1
  redmine_mermaid_macro          0.0.1
  redmine_my_page                0.1.12
  redmine_scm_extensions         0.4.0
  redmine_shady                  0.5.0
  redmine_silencer               0.4.1
  redmine_tab                    0.4.0
  redmine_theme_changer          0.2.0
  sidebar                        0.1.2
  sidebar_hide                   0.0.7
  unread_issues                  2.2.0
  vault                          0.3.3

**Comment by chriswnl** [comment]
I'm not familiar with Bitnami. But I've run this on Beanstalk and 
several ubuntu hosts too.

Have you tried running the rake task from the htdocs/ directory and not 
the plugins one? Usually, you'd install Redmine plugins using that rake 
command from the redmine root.


On 28/12/17 20:56, MatthewPaulGithub wrote:
> bitnami@ip-172-30-0-36:/opt/bitnami/apps/redmine/htdocs/plugins$ rake 
> redmine:plugins:migrate RAILS_ENV=production
>
> (in /opt/bitnami/apps/redmine/htdocs)
> rake aborted!
> LoadError: Unable to autoload constant AccountControllerPatch, 
> expected 
> /opt/bitnami/apps/redmine/htdocs/plugins/google_authenticator/lib/account_controller_patch.rb 
> to define it
> /opt/bitnami/apps/redmine/htdocs/plugins/redmine_local_avatars/init.rb:33:in 
> |block in <top (required)>' 
> /opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in|<top 
> (required)>'
> /opt/bitnami/apps/redmine/htdocs/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in 
> |<top (required)>' 
> /opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in|block 
> in <top (required)>'
> /opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in |each' 
> /opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in|<top 
> (required)>'
> /opt/bitnami/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
>
The problem starts here ^^ when the Rakefile loads the environment, I 
believe.

**Comment by MatthewPaulGithub** [comment]
Just tried that, same error, and generally I always install from plugins in any case and it seems to work.  Not to worry, I really think it may be my plugins - it mentions the local avatar plugin and the a_common_libs in that same bunch of messages so maybe it's something to do with them. Like I say, not a big deal.

Btw if you haven't checked out bitnami, you should. It's excellent for installing loads of pre-configured stacks with no hassle onto a google/aws/azure/etc cloud to try stuff out or, if you're technically challenged like me, to actually run it long term without spending days/weeks on reading manuals :-)

Thanks again for looking at that for me, all the best!

**Comment by chriswnl** [comment]
Happy to try. I'm quite tech savvy so happy to do the manuals and usually I deploy through the elastic beanstalk cli.

Anyway, having a look with the tools (and accounts) I have to hand, I setup an amazon EC2 instance with a bitnami redmine image. After install, I SSHed to the box, installed the plugin and it ran fine. Here's the total output, including my 'oopses' 

```shell
[bitnami@ip-xxx-xxx-xxx-xxx ~]$ cd /opt/bitnami/apps/redmine/htdocs/
[bitnami@ip-xxx-xxx-xxx-xxx htdocs]$ ls
app           bin     config.ru        db   extra  Gemfile       lib  plugins  Rakefile     script  tmp
appveyor.yml  config  CONTRIBUTING.md  doc  files  Gemfile.lock  log  public   README.rdoc  test    vendor

[bitnami@ip-xxx-xxx-xxx-xxx htdocs]$ git clone https://github.com/chriswnl/redmine_google_authenticator.git plugins/google_authenticator
Cloning into 'plugins/google_authenticator'...
remote: Counting objects: 116, done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 116 (delta 44), reused 115 (delta 43), pack-reused 0
Receiving objects: 100% (116/116), 74.28 KiB | 12.38 MiB/s, done.
Resolving deltas: 100% (44/44), done.
[bitnami@ip-xxx-xxx-xxx-xxx htdocs]$ echo $RAILS_ENV

[bitnami@ip-xxx-xxx-xxx-xxx htdocs]$ RAILS_ENV=production rake redmine:plugins
rake aborted!
Gem::LoadError: You have already activated rake 12.0.0, but your Gemfile requires rake 12.2.1. Prepending `bundle exec` to your command may solve this.
/opt/bitnami/apps/redmine/htdocs/config/boot.rb:4:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/application.rb:1:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/Rakefile:5:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/opt/bitnami/apps/redmine/htdocs/config/boot.rb:4:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/application.rb:1:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)


[bitnami@ip-xxx-xxx-xxx-xxx htdocs]$ RAILS_ENV=production bundle exec rake redmine:plugins
Rails Error: Unable to access log file. Please ensure that /opt/bitnami/apps/redmine/htdocs/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /opt/bitnami/apps/redmine/htdocs/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
Migrating google_authenticator (Google Authenticator)...
Migrating to CreateTwoStepAuths (1)
== 1 CreateTwoStepAuths: migrating ============================================
-- create_table(:two_step_auths)
   -> 0.2065s
== 1 CreateTwoStepAuths: migrated (0.2066s) ===================================

[bitnami@ip-xxx-xxx-xxx-xxx htdocs]$ exit

```
The first error was a rake version issue so I prefixed my rake command with `bundle exec`.
The other errors are just because bitnami user doesn't have perms set up on this box to allow it to write to the log files but that didn't stop it from installing.

Once rebooted, or the server restarted, the plugin appeared for me under admin.

Hopefully this can help you troubleshoot.
cw

**Comment by MatthewPaulGithub** [comment]
Wow, that's pretty cool you were able to test that right off the bat like that.  Then I think it must be one of the plugins that I have installed, which doesn't surprise me, I have a ton of them, I'm always interested in seeing what the different plugins do. Redmine is so cool like that, so flexible.

I did just now try again to do the install with a trace. I copy it here for interest but not for further effort from you - I'm sure you have 'real life' work to do etc.  As above, and here, the trace mentions something about a Polyglot - which sounds like something you hack up when you have a cold, but anyways, for the record here it is. As you say, I will probably try your plugin in a clean instance at some point, I do think it's a very cool addition, and I see google auth all over the place with cryptocurrencies and the like.

MP

>>>
bitnami@ip-172-30-0-36:/opt/bitnami/apps/redmine/htdocs/plugins$ rake db:migrate NAME=google_authenticator RAILS_ENV=production  --trace
(in /opt/bitnami/apps/redmine/htdocs)
rake aborted!
LoadError: Unable to autoload constant AccountControllerPatch, expected /opt/bitnami/apps/redmine/htdocs/plugins/google_authenticator/lib/account_controller_patch.rb to define it
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:495:in `load_missing_constant'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_local_avatars/init.rb:33:in `block in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `instance_exec'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `block in simple'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:347:in `call'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `run_tasks_blocks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:452:in `run_tasks_blocks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:453:in `load_tasks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/opt/bitnami/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:703:in `raw_load_rakefile'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:104:in `block in load_rakefile'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:103:in `load_rakefile'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:82:in `block in run'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/rake:23:in `load'
/opt/bitnami/ruby/bin/rake:23:in `<main>'

Caused by:
Polyglot::PolyglotLoadError: Failed to load /opt/bitnami/apps/redmine/htdocs/config/environment using extensions rb
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:55:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:68:in `rescue in require'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:194:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `run_tasks_blocks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:452:in `run_tasks_blocks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:453:in `load_tasks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/opt/bitnami/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:703:in `raw_load_rakefile'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:104:in `block in load_rakefile'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:103:in `load_rakefile'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:82:in `block in run'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/rake:23:in `load'
/opt/bitnami/ruby/bin/rake:23:in `<main>'
bitnami@ip-172-30-0-36:/opt/bitnami/apps/redmine/htdocs/plugins$
